require 'pry'
require 'byebug'
require 'mysql2'
require 'require_all'
require 'logger'
require 'rest-client'
require 'net/http'
require 'json'
require 'active_support/all'
require 'aws-sdk'
require 'dotenv/load'

require_all 'lib/**/**.rb'
require_all 'app/**/**.rb'
